version: '3'
services:
  news-getter:
    image: news.getter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    restart: always
    networks:
      - shared_network

networks:
  shared_network:
    external: true